[package]
name = "rename-legal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
emojis = "0.5.2"
regex = "1.7.1"
unicode-segmentation = "1.10.1"
